site_name: Teng's Blog
site_description: 个人博客
site_url: https://zhangteng520.github.io
theme:
  name: material
  features:
    ##- navigation.tracking
    - navigation.tabs
    ## - navigation.indexes
    - content.code.annotate  # 确保这个存在
    - content.tabs.link  # 确保这个存在
    

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog